interface Product {
  id: number;
  name: string;
  category: string;
  image: string;
  description: string;
}

export const PRODUCTS: Product[] = [
  // New Products
  {
    id: 1,
    name: "Biryani Mix",
    category: "Gravy Mix",
    image: "/biryani_mix.jpg",
    description: "Authentic biryani mix for a rich taste.",
  },
  {
    id: 2,
    name: "Chicken Gravy",
    category: "Gravy Mix",
    image: "/chicken_gravy.jpg",
    description: "A savory and aromatic chicken gravy.",
  },
  {
    id: 3,
    name: "Egg Curry",
    category: "Gravy Mix",
    image: "/egg_curry.jpg",
    description: "A rich and flavorful egg curry paste.",
  },
  {
    id: 4,
    name: "Kaju Curry",
    category: "Gravy Mix",
    image: "/kaju_curry.jpg",
    description: "A rich and creamy cashew-based curry.",
  },
  {
    id: 5,
    name: "Methi Matar",
    category: "Gravy Mix",
    image: "/methi_matar.jpg",
    description: "A delicious methi matar mix with aromatic spices.",
  },
  {
    id: 6,
    name: "Mushroom Matar",
    category: "Gravy Mix",
    image: "/mushroom_matar.jpg",
    description: "A savory mushroom and peas curry mix.",
  },
  {
    id: 7,
    name: "Mutton Gravy",
    category: "Gravy Mix",
    image: "/mutton_gravy.jpg",
    description: "Rich and savory mutton gravy.",
  },
  {
    id: 8,
    name: "Palak Panner Masala",
    category: "Gravy Mix",
    image: "/palak_panner_masala.jpg",
    description: "A creamy spinach and paneer curry mix.",
  },
  {
    id: 9,
    name: "Panner Butter Masala",
    category: "Gravy Mix",
    image: "/panner_butter_masala.jpg",
    description: "A creamy and rich paneer butter gravy.",
  },
  {
    id: 10,
    name: "Veg Bhunna Masala",
    category: "Gravy Mix",
    image: "/veg_bhuna.jpg",
    description: "A flavorful veg bhuna masala mix.",
  },
  {
    id: 11,
    name: "Veg Bhunna Khemma Masala",
    category: "Gravy Mix",
    image: "/veg_bhunna_khemma.jpg",
    description: "Aromatic veg bhunna khemma mix for a spicy dish.",
  },

  // Gravy Mix Products
  {
    id: 12,
    name: "KALA RASSA PASTE (NASHIK SPL.)",
    category: "Gravy Mix",
    image: "/turmeric.jpg",
    description: "Pure and fresh turmeric powder.",
  },
  {
    id: 13,
    name: "MISAL PAV RASSA PASTE",
    category: "Gravy Mix",
    image: "/cumin.jpg",
    description: "Aromatic cumin seeds.",
  },
  {
    id: 14,
    name: "SEV BHAJI RASSA PASTE (JALGAON SPL.)",
    category: "Gravy Mix",
    image: "/garam-masala.jpg",
    description: "A blend of flavorful spices.",
  },
  {
    id: 15,
    name: "PATOLI RASSA PASTE (NAGPUR SPL.)",
    category: "Gravy Mix",
    image: "/oregano.jpg",
    description: "Fresh dried oregano leaves.",
  },
  {
    id: 16,
    name: "PANDHARA RASSA PASTE (KOLHAPUR SPL.)",
    category: "Gravy Mix",
    image: "/bbq-seasoning.jpg",
    description: "Perfect for grilling and barbecue.",
  },
  {
    id: 17,
    name: "TAMBADA RASSA PASTE (KOLHAPUR SPL.)",
    category: "Gravy Mix",
    image: "/bbq-seasoning.jpg",
    description: "Perfect for grilling and barbecue.",
  },
  {
    id: 18,
    name: "SAOJI RASSA PASTE (NAGPUR SPL.)",
    category: "Gravy Mix",
    image: "/cumin.jpg",
    description: "Spicy and flavorful Nagpuri-style paste.",
  },
  {
    id: 19,
    name: "MUTTON GRAVY PASTE",
    category: "Gravy Mix",
    image: "/garam-masala.jpg",
    description: "Rich and savory mutton gravy.",
  },
  {
    id: 20,
    name: "DAL MAKHANI MIX",
    category: "Gravy Mix",
    image: "/oregano.jpg",
    description: "A blend of spices for rich dal makhani.",
  },
  {
    id: 21,
    name: "DAL MASH MIX",
    category: "Gravy Mix",
    image: "/turmeric.jpg",
    description: "Flavorful dal mash mix for authentic taste.",
  },
  {
    id: 22,
    name: "AKKHA MASOOR MIX",
    category: "Gravy Mix",
    image: "/cumin.jpg",
    description: "Spiced Akkha Masoor for a hearty meal.",
  },
  {
    id: 23,
    name: "MUSHROOM CURRY MIX",
    category: "Gravy Mix",
    image: "/garam-masala.jpg",
    description: "A delicious mushroom curry mix.",
  },
  {
    id: 24,
    name: "KAJU CURRY MIX",
    category: "Gravy Mix",
    image: "/oregano.jpg",
    description: "A rich and creamy cashew-based curry.",
  },
  {
    id: 25,
    name: "TIKKA MARINADE PASTE",
    category: "Gravy Mix",
    image: "/bbq-seasoning.jpg",
    description: "Perfect marinade for tikka preparation.",
  },
  {
    id: 26,
    name: "TANDOORI MARINADE PASTE",
    category: "Gravy Mix",
    image: "/bbq-seasoning.jpg",
    description: "Classic tandoori marinade paste for grilling.",
  },
  {
    id: 27,
    name: "KABAB MARINADE PASTE",
    category: "Gravy Mix",
    image: "/turmeric.jpg",
    description: "Flavorful kabab marinade for a smoky taste.",
  },
  {
    id: 28,
    name: "FISH MARINADE PASTE",
    category: "Gravy Mix",
    image: "/cumin.jpg",
    description: "A tangy and spicy marinade for fish.",
  },
  {
    id: 29,
    name: "HYDERABADI BIRYANI MIX",
    category: "Gravy Mix",
    image: "/garam-masala.jpg",
    description: "Authentic biryani mix for a rich taste.",
  },
  {
    id: 30,
    name: "SINDHI BIRYANI MIX",
    category: "Gravy Mix",
    image: "/oregano.jpg",
    description: "A Sindhi-style biryani with bold spices.",
  },
  {
    id: 31,
    name: "AWADHI BIRYANI MIX",
    category: "Gravy Mix",
    image: "/bbq-seasoning.jpg",
    description: "Aromatic Awadhi-style biryani mix.",
  },
  {
    id: 32,
    name: "EGG BIRYANI MIX",
    category: "Gravy Mix",
    image: "/turmeric.jpg",
    description: "Egg-based biryani mix for a flavorful dish.",
  },
  {
    id: 33,
    name: "VEG BIRYANI MIX",
    category: "Gravy Mix",
    image: "/cumin.jpg",
    description: "Veg biryani mix for a rich vegetarian meal.",
  },
  {
    id: 34,
    name: "MUSHROOM YAKHNI PULAV MIX",
    category: "Gravy Mix",
    image: "/garam-masala.jpg",
    description: "Flavorful mushroom yakhni pulav mix.",
  },
  {
    id: 35,
    name: "VEG HALEEM MIX",
    category: "Gravy Mix",
    image: "/oregano.jpg",
    description: "Vegetarian Haleem mix with rich spices.",
  },
  {
    id: 36,
    name: "VEG BHUNA KEEMA MIX",
    category: "Gravy Mix",
    image: "/bbq-seasoning.jpg",
    description: "Aromatic bhuna keema mix for a spicy meal.",
  },
  {
    id: 37,
    name: "SOL KADHI MIX",
    category: "Gravy Mix",
    image: "/turmeric.jpg",
    description: "Tangy and refreshing Sol Kadhi mix.",
  },
  {
    id: 38,
    name: "CHICKEN GRAVY PASTE",
    category: "Gravy Mix",
    image: "/cumin.jpg",
    description: "A savory and aromatic chicken gravy.",
  },
  {
    id: 39,
    name: "FISH CURRY PASTE",
    category: "Gravy Mix",
    image: "/garam-masala.jpg",
    description: "A spicy fish curry paste.",
  },
  {
    id: 40,
    name: "EGG CURRY PASTE",
    category: "Gravy Mix",
    image: "/oregano.jpg",
    description: "A rich and flavorful egg curry paste.",
  },
  {
    id: 41,
    name: "BUTTER CHICKEN GRAVY PASTE",
    category: "Gravy Mix",
    image: "/bbq-seasoning.jpg",
    description: "Creamy butter chicken gravy paste.",
  },
  {
    id: 42,
    name: "PANEER BUTTER GRAVY PASTE",
    category: "Gravy Mix",
    image: "/turmeric.jpg",
    description: "A creamy and rich paneer butter gravy.",
  },
  {
    id: 43,
    name: "ALL PURPOSE GRAVY PASTE",
    category: "Gravy Mix",
    image: "/cumin.jpg",
    description: "Versatile all-purpose gravy paste.",
  },

  // Seasoning Products
  {
    id: 44,
    name: "MAGGIE MASALA",
    category: "Seasonings",
    image: "/spices.jpg",
    description: "Classic Maggi masala for instant flavor.",
  },
  {
    id: 45,
    name: "TANGY TOMATO",
    category: "Seasonings",
    image: "/spices.jpg",
    description: "A tangy tomato seasoning for snacks.",
  },
  {
    id: 46,
    name: "MASALA PAV",
    category: "Seasonings",
    image: "/spices.jpg",
    description: "A blend of spices for masala pav.",
  },
  {
    id: 47,
    name: "CHAT MASALA",
    category: "Seasonings",
    image: "/spices.jpg",
    description: "A tangy seasoning for chaat dishes.",
  },
  {
    id: 48,
    name: "PAV BHAJI MASALA",
    category: "Seasonings",
    image: "/spices.jpg",
    description: "The perfect masala for pav bhaji.",
  },
  {
    id: 49,
    name: "TANDOORI MASALA",
    category: "Seasonings",
    image: "/spices.jpg",
    description: "Flavorful tandoori masala for grilling.",
  },
  {
    id: 50,
    name: "GARLIC SEASONING",
    category: "Seasonings",
    image: "/spices.jpg",
    description: "Garlic seasoning for a rich flavor.",
  },
];
